version: '3.8'
services:
  web:
    build: .
    command: ['/freelance/script.sh']
    volumes:
      - .:/freelance
    ports:
      - 8000:8000
    depends_on:
      - db
    env_file:
      - .env-compose
  db:
    image: postgres:alpine3.19
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - .env-compose
volumes:
  postgres_data:
